sudo: required
# .travis.yml
language: node_js
node_js:
    - 6
    - 6.1
    - 5.11
    - 0.6
before_install:
    - npm install mocha -g
branches:
    only:
        - master
matrix:
    allow_failures:
        - node_js: 6